# Generated by Django 2.1.5 on 2021-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_auto_20210804_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='tanggalMaterialDiubah',
            new_name='tanggalDiubah',
        ),
        migrations.AddField(
            model_name='material',
            name='tanggalMulaiBerlaku',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_diubah',
            field=models.BooleanField(default=False),
        ),
    ]
