# Generated by Django 2.1.5 on 2021-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_auto_20210804_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tanggalMulaiBerlaku',
            field=models.DateField(),
        ),
    ]
