# Generated by Django 2.1.5 on 2021-08-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_auto_20210804_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='penggantiMaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penggantiMaterial_material_set', to='produk.Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='penyusunProduk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penyusunProduk_material_set', to='produk.Material'),
        ),
    ]
