# Generated by Django 2.1.5 on 2021-08-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_auto_20210807_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tanggalMulaiBerlaku',
            field=models.DateField(blank=True, null=True),
        ),
    ]
