# Generated by Django 2.1.5 on 2021-08-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_auto_20210807_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='is_diubah',
            new_name='is_ganti',
        ),
    ]
