# Generated by Django 2.1.5 on 2021-08-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0007_auto_20210808_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='tanggalDiubah',
            new_name='tanggalGanti',
        ),
    ]
