# Generated by Django 2.1.5 on 2021-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0009_auto_20210808_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='is_ganti',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
