# Generated by Django 2.1.5 on 2021-08-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0011_auto_20210808_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='is_ganti',
            new_name='is_berlaku',
        ),
    ]
