# Generated by Django 2.1.5 on 2021-08-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0012_auto_20210808_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='is_berlaku',
            field=models.BooleanField(default=True),
        ),
    ]
