# Generated by Django 2.1.5 on 2021-08-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0013_auto_20210810_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
