# Generated by Django 2.1.5 on 2021-08-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0014_auto_20210831_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='is_berlaku',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
