# Generated by Django 2.1.5 on 2021-09-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0016_auto_20210902_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='varian',
        ),
        migrations.AddField(
            model_name='material',
            name='varian',
            field=models.ForeignKey(default='V01', on_delete=django.db.models.deletion.CASCADE, to='produk.Varian', to_field='idVarian'),
            preserve_default=False,
        ),
    ]
