# Generated by Django 2.1.5 on 2021-08-01 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KebutuhanMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlahMaterialPerCycleTime', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Material')),
            ],
        ),
        migrations.CreateModel(
            name='LiniProduksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLiniProduksi', models.CharField(max_length=255, unique=True)),
                ('waktuSiklus', models.IntegerField()),
                ('waktuMulaiProduksi', models.TimeField()),
                ('waktuSelesaiProduksi', models.TimeField()),
                ('jumlahStasiunKerja', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelOperator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PengirimanMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlahMaterialTiapPengiriman', models.IntegerField()),
                ('kebutuhanMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.KebutuhanMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PeralatanProduksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPeralatan', models.CharField(max_length=255, unique=True)),
                ('jenisPeralatan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProses', models.CharField(max_length=255, unique=True)),
                ('namaProses', models.CharField(max_length=255)),
                ('durasiProses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StasiunKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idStasiunKerja', models.CharField(max_length=255, unique=True)),
                ('nomorStasiunKerja', models.IntegerField()),
                ('sisiStasiunKerja', models.CharField(choices=[('Kanan', 'Kanan'), ('Kiri', 'Kiri')], max_length=255)),
                ('liniProduksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.LiniProduksi', to_field='idLiniProduksi')),
            ],
        ),
        migrations.CreateModel(
            name='TargetProduksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggalProduksi', models.DateField()),
                ('target', models.IntegerField()),
                ('capaian', models.IntegerField(default=0)),
                ('persentaseCapaian', models.FloatField(blank=True, null=True)),
                ('liniProduksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.LiniProduksi', to_field='idLiniProduksi')),
            ],
        ),
        migrations.AddField(
            model_name='proses',
            name='stasiunKerja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.StasiunKerja', to_field='idStasiunKerja'),
        ),
        migrations.AddField(
            model_name='peralatanproduksi',
            name='proses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.Proses', to_field='idProses'),
        ),
        migrations.AddField(
            model_name='peralatanproduksi',
            name='stasiunKerja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.StasiunKerja', to_field='idStasiunKerja'),
        ),
        migrations.AddField(
            model_name='pengirimanmaterial',
            name='stasiunKerja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.StasiunKerja', to_field='idStasiunKerja'),
        ),
        migrations.AddField(
            model_name='operator',
            name='proses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.Proses', to_field='idProses'),
        ),
        migrations.AddField(
            model_name='operator',
            name='stasiunKerja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.StasiunKerja', to_field='idStasiunKerja'),
        ),
        migrations.AddField(
            model_name='operator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_sk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kebutuhanmaterial',
            name='proses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.Proses', to_field='idProses'),
        ),
        migrations.AddField(
            model_name='kebutuhanmaterial',
            name='stasiunKerja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.StasiunKerja', to_field='idStasiunKerja'),
        ),
    ]
