# Generated by Django 2.1.5 on 2021-08-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebutuhanmaterial',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produk.Material'),
        ),
    ]
