# Generated by Django 2.1.5 on 2021-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0003_auto_20210809_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebutuhanmaterial',
            name='jumlahMaterialPerCycleTime',
            field=models.IntegerField(default=0),
        ),
    ]
