# Generated by Django 2.1.5 on 2021-08-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0005_auto_20210809_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='proses',
            name='is_berlaku',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kebutuhanmaterial',
            name='jumlahMaterialPerCycleTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kebutuhanmaterial',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kebutuhanMaterial', to='produk.Material'),
        ),
    ]
