# Generated by Django 2.1.5 on 2021-08-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0006_auto_20210809_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='proses',
            name='tanggalMulaiBerlaku',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proses',
            name='tanggalSelesaiBerlaku',
            field=models.DateField(blank=True, null=True),
        ),
    ]
