# Generated by Django 2.1.5 on 2021-08-11 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0007_auto_20210810_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gangguan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGangguan', models.CharField(max_length=255, unique=True)),
                ('waktuMulaiGangguan', models.TimeField(blank=True, null=True)),
                ('waktuSelesaiGangguan', models.TimeField(blank=True, null=True)),
                ('penyebab', models.TextField(blank=True, null=True)),
                ('stasiunKerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.StasiunKerja', to_field='idStasiunKerja')),
            ],
        ),
        migrations.AlterField(
            model_name='pengirimanmaterial',
            name='kebutuhanMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengirimanMaterial', to='liniProduksi.KebutuhanMaterial'),
        ),
    ]
