# Generated by Django 2.1.5 on 2021-08-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0009_auto_20210811_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gangguan',
            name='idGangguan',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
