# Generated by Django 2.1.5 on 2021-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0011_gangguan_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='gangguan',
            name='durasiGangguan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
