# Generated by Django 2.1.5 on 2021-08-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0012_gangguan_durasigangguan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gangguan',
            old_name='kategori',
            new_name='status',
        ),
    ]
