# Generated by Django 2.1.5 on 2021-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0013_auto_20210811_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='gangguan',
            name='tanggalGangguan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
