# Generated by Django 2.1.5 on 2021-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0014_gangguan_tanggalgangguan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gangguan',
            name='waktuMulaiLiniProduksiTerhenti',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gangguan',
            name='waktuSelesaiLiniProduksiTerhenti',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
