# Generated by Django 2.1.5 on 2021-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0015_auto_20210811_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='gangguan',
            name='durasiLiniProduksiTerhenti',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
