# Generated by Django 2.1.5 on 2021-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0016_gangguan_durasiliniproduksiterhenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetproduksi',
            name='waktuMulaiProduksiAktual',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetproduksi',
            name='waktuSelesaiProduksiAktual',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
