# Generated by Django 2.1.5 on 2021-08-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0017_auto_20210813_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetproduksi',
            name='tanggalProduksi',
            field=models.DateField(unique=True),
        ),
    ]
