# Generated by Django 2.1.5 on 2021-08-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0018_auto_20210814_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetproduksi',
            name='downtime',
            field=models.IntegerField(default=0),
        ),
    ]
