# Generated by Django 2.1.5 on 2021-08-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0019_targetproduksi_downtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetproduksi',
            name='tanggalProduksi',
            field=models.DateField(),
        ),
    ]
