# Generated by Django 2.1.5 on 2021-08-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0020_auto_20210814_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetproduksi',
            name='is_lembur',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
