# Generated by Django 2.1.5 on 2021-08-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0021_targetproduksi_is_lembur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetproduksi',
            name='is_lembur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
