# Generated by Django 2.1.5 on 2021-08-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0022_auto_20210814_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetproduksi',
            name='is_lembur',
            field=models.CharField(blank=True, choices=[('Lembur', 'Lembur'), ('Tidak lembur', 'Tidak lembur')], max_length=200, null=True),
        ),
    ]
