# Generated by Django 2.1.5 on 2021-08-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0023_auto_20210814_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaktuIstirahat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktuMulaiIstirahat', models.TimeField()),
                ('waktuSelesaiIstirahat', models.TimeField()),
                ('liniProduksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.LiniProduksi', to_field='idLiniProduksi')),
            ],
        ),
    ]
