# Generated by Django 2.1.5 on 2021-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0024_waktuistirahat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waktuistirahat',
            name='liniProduksi',
        ),
        migrations.AddField(
            model_name='liniproduksi',
            name='waktuMulaiIstirahat',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liniproduksi',
            name='waktuSelesaiIstirahat',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='WaktuIstirahat',
        ),
    ]
