# Generated by Django 2.1.5 on 2021-08-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0027_kebutuhanmaterial_jumlahmaterialtersedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebutuhanmaterial',
            name='jumlahMaterialTersedia',
            field=models.IntegerField(default=0),
        ),
    ]
