# Generated by Django 2.1.5 on 2021-08-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0028_auto_20210820_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kebutuhanmaterial',
            old_name='jumlahMaterialTersedia',
            new_name='jumlahMaterial',
        ),
    ]
