# Generated by Django 2.1.5 on 2021-08-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0029_auto_20210820_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kebutuhanmaterial',
            old_name='jumlahMaterial',
            new_name='jumlahMaterialKumulatif',
        ),
    ]
