# Generated by Django 2.1.5 on 2021-08-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0030_auto_20210820_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liniproduksi',
            name='waktuMulaiIstirahat',
        ),
        migrations.RemoveField(
            model_name='liniproduksi',
            name='waktuMulaiProduksi',
        ),
        migrations.RemoveField(
            model_name='liniproduksi',
            name='waktuSelesaiIstirahat',
        ),
        migrations.RemoveField(
            model_name='liniproduksi',
            name='waktuSelesaiProduksi',
        ),
        migrations.AddField(
            model_name='targetproduksi',
            name='waktuMulaiProduksi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetproduksi',
            name='waktuSelesaiProduksi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetproduksi',
            name='tanggalProduksi',
            field=models.DateField(unique=True),
        ),
    ]
