# Generated by Django 2.1.5 on 2021-08-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0031_auto_20210827_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TargetProduksi',
            new_name='ProduksiHarian',
        ),
    ]
