# Generated by Django 2.1.5 on 2021-08-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0032_auto_20210827_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaktuIstirahat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktuMulaiIstirahat', models.TimeField()),
                ('waktuSelesaiIstirahat', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='produksiharian',
            name='waktuMulaiProduksi',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='produksiharian',
            name='waktuSelesaiProduksi',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='waktuistirahat',
            name='produksiHarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.ProduksiHarian'),
        ),
    ]
