# Generated by Django 2.1.5 on 2021-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0033_auto_20210827_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='user',
        ),
        migrations.AddField(
            model_name='operator',
            name='namaLengkap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
