# Generated by Django 2.1.5 on 2021-08-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0035_auto_20210828_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='produksiharian',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
