# Generated by Django 2.1.5 on 2021-08-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0036_produksiharian_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='produksiharian',
            name='is_libur',
            field=models.CharField(choices=[('Libur', 'Libur'), ('Tidak libur', 'Tidak libur')], default='Tidak libur', max_length=200),
        ),
    ]
