# Generated by Django 2.1.5 on 2021-08-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0038_auto_20210830_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='produksiharian',
            name='alasanLibur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produksiharian',
            name='is_libur',
            field=models.CharField(choices=[('Libur', 'Libur'), ('Tidak libur', 'Tidak libur')], default='Tidak libur', max_length=200),
        ),
    ]
