# Generated by Django 2.1.5 on 2021-08-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0039_auto_20210831_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produksiharian',
            name='alasanLibur',
            field=models.TextField(default='Tidak libur'),
        ),
    ]
