# Generated by Django 2.1.5 on 2021-09-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0040_auto_20210831_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='produksiharian',
            name='kondisiIstirahat',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Customize', 'Customize')], default='Normal', max_length=200),
        ),
        migrations.AddField(
            model_name='waktuistirahat',
            name='kondisi',
            field=models.CharField(default='Normal', max_length=200),
            preserve_default=False,
        ),
    ]
