# Generated by Django 2.1.5 on 2021-09-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0043_auto_20210903_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetharian',
            name='liniProduksi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.LiniProduksi', to_field='idLiniProduksi'),
        ),
        migrations.AlterField(
            model_name='targetharian',
            name='tanggal',
            field=models.DateField(null=True),
        ),
    ]
