# Generated by Django 2.1.5 on 2021-09-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0044_auto_20210903_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetharian',
            name='liniProduksi',
        ),
        migrations.AddField(
            model_name='targetharian',
            name='produksiHarian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.ProduksiHarian'),
        ),
    ]
