# Generated by Django 2.1.5 on 2021-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0045_auto_20210903_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produksiharian',
            name='capaian',
        ),
        migrations.AddField(
            model_name='targetharian',
            name='capaian',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
