# Generated by Django 2.1.5 on 2021-09-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0047_auto_20210903_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetharian',
            name='waktuMulaiProduksiAktual',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetharian',
            name='waktuSelesaiProduksiAktual',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
