# Generated by Django 2.1.5 on 2021-09-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0049_targetmingguan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetmingguan',
            name='capaian',
        ),
        migrations.AddField(
            model_name='targetmingguan',
            name='tahun',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='targetmingguan',
            name='minggu',
            field=models.IntegerField(null=True),
        ),
    ]
