# Generated by Django 2.1.5 on 2021-09-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liniProduksi', '0050_auto_20210903_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produksiharian',
            name='waktuMulaiProduksi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produksiharian',
            name='waktuSelesaiProduksi',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
