# Generated by Django 2.1.5 on 2021-09-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0017_auto_20210902_1802'),
        ('liniProduksi', '0051_auto_20210903_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetBulanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('bulan', models.IntegerField(null=True)),
                ('tahun', models.IntegerField(null=True)),
                ('liniProduksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.LiniProduksi', to_field='idLiniProduksi')),
                ('varian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Varian', to_field='idVarian')),
            ],
        ),
        migrations.CreateModel(
            name='TargetTahunan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('tahun', models.IntegerField(null=True)),
                ('liniProduksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.LiniProduksi', to_field='idLiniProduksi')),
                ('varian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Varian', to_field='idVarian')),
            ],
        ),
    ]
