# Generated by Django 2.1.5 on 2021-08-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEO', models.CharField(max_length=255, unique=True)),
                ('namaPengusul', models.CharField(max_length=255, unique=True)),
                ('departemenPengusul', models.CharField(max_length=255, unique=True)),
                ('keterangan', models.CharField(max_length=500, unique=True)),
                ('tanggalPengajuan', models.DateField()),
                ('is_disetujui', models.BooleanField(blank=True, null=True)),
                ('tanggalDisetujui', models.DateField(blank=True, null=True)),
                ('tanggalPerubahanBerlaku', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Material')),
            ],
        ),
    ]
