# Generated by Django 2.1.5 on 2021-08-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringOrder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineeringorder',
            old_name='tanggalDisetujui',
            new_name='tanggalPersetujuan',
        ),
        migrations.AlterField(
            model_name='engineeringorder',
            name='is_disetujui',
            field=models.BooleanField(blank=True, choices=[(0, 'Tidak'), (1, 'Iya')], null=True),
        ),
    ]
