# Generated by Django 2.1.5 on 2021-08-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringOrder', '0003_auto_20210803_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringorder',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produk.Material'),
        ),
    ]
