# Generated by Django 2.1.5 on 2021-08-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringOrder', '0009_auto_20210804_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringorder',
            name='is_disetujui',
            field=models.NullBooleanField(),
        ),
    ]
