# Generated by Django 2.1.5 on 2021-08-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringOrder', '0011_auto_20210805_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringorder',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eo', to='produk.Material'),
        ),
    ]
