# Generated by Django 2.1.5 on 2021-08-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringOrder', '0012_auto_20210809_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringorder',
            name='is_prosesBaru',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
