# Generated by Django 2.1.5 on 2021-08-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringOrder', '0013_engineeringorder_is_prosesbaru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringorder',
            name='keterangan',
            field=models.TextField(),
        ),
    ]
