from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views, viewsStasiunKerja, viewsStasiunKerjaDetail, viewsMaterial, viewsProses, viewsPeralatanProduksi, viewsOperator, viewsLiniProduksi_harian, viewsPengirimanMaterial, viewsGangguan
app_name = 'liniProduksi'

urlpatterns = [
    path('gangguanStasiunKerja/gangguanSelesai/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.gangguanSelesai, name='gangguanSelesai'),
    path('gangguanStasiunKerja/indikasiMasalah/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.gangguanForm, name='gangguanForm'),
    path('gangguanStasiunKerja/liniProduksiTerhenti/<str:idStasiunKerjaInput>/<str:idGangguanInput>', viewsGangguan.liniProduksiTerhenti, name='liniProduksiTerhenti'),
    path('gangguanStasiunKerja/indikasiMasalah/<str:idStasiunKerjaInput>', viewsGangguan.indikasiMasalah, name='indikasiMasalah'),
    path('gangguanStasiunKerja/<str:idStasiunKerjaInput>', viewsGangguan.gangguanStasiunKerja, name='gangguanSK'),
    path('gangguanStasiunKerja/semua/', viewsGangguan.gangguan_semua, name='gangguanSemua'),
    path('gangguanStasiunKerja/', viewsGangguan.gangguan, name='gangguan'),
    path('updateMaterial/<str:update_id>', viewsMaterial.updateMaterial, name='updateMaterial'),
    path('deleteMaterial/<str:delete_id>', viewsMaterial.deleteMaterial, name='deleteMaterial'),
    path('updateStasiunKerja/<str:update_id>', viewsStasiunKerja.updateStasiunKerja, name='updateStasiunKerja'),
    path('deleteStasiunKerja/<str:delete_id>', viewsStasiunKerja.deleteStasiunKerja, name='deleteStasiunKerja'),
    path('updateLiniProduksi/<str:update_id>', views.updateLiniProduksi, name='updateLiniProduksi'),
    path('deleteLiniProduksi/<str:delete_id>', views.deleteLiniProduksi, name='deleteLiniProduksi'),
    path('updateProses/<str:update_id>', viewsProses.updateProses, name='updateProses'),
    path('deleteProses/<str:delete_id>', viewsProses.deleteProses, name='deleteProses'),
    path('updatePeralatanProduksi/<str:update_id>', viewsPeralatanProduksi.updatePeralatanProduksi, name='updatePeralatanProduksi'),
    path('deletePeralatanProduksi/<str:delete_id>', viewsPeralatanProduksi.deletePeralatanProduksi, name='deletePeralatanProduksi'),
    path('updateOperator/<str:update_id>', viewsOperator.updateOperator, name='updateOperator'),
    path('deleteOperator/<str:delete_id>', viewsOperator.deleteOperator, name='deleteOperator'),
    path('newProses/', viewsProses.newProses, name='newProses'),
    path('newPeralatanProduksi/', viewsPeralatanProduksi.newPeralatanProduksi, name='newPeralatanProduksi'),
    path('newKebutuhanMaterial/', viewsMaterial.newMaterial, name='newKebutuhanMaterial'),
    path('newLiniProduksi/', views.newLiniProduksi, name='newLiniProduksi'),
    path('newStasiunKerja/',viewsStasiunKerja.newStasiunKerja, name='newStasiunKerja'),
    path('newOperator/',viewsOperator.newOperator, name='newOperator'),
    path('newPengirimanMaterial/',viewsPengirimanMaterial.newPengirimanMaterial, name='newPengirimanMaterial'),
    path('updatePengirimanMaterial/<str:update_id>', viewsPengirimanMaterial.updatePengirimanMaterial,
         name='updatePengirimanMaterial'),
    path('deletePengirimanMaterial/<str:delete_id>', viewsPengirimanMaterial.deletePengirimanMaterial,
         name='deletePengirimanMaterial'),
    path('updateTargetHarian/<str:update_id>', viewsLiniProduksi_harian.updateTargetHarian, name='updateTargetHarian'),
    path('deleteTargetHarian/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetHarian, name='deleteTargetHarian'),
    path('produksiHarian/newTargetHarian/<str:produksiHarianInput>',viewsLiniProduksi_harian.newTargetHarian, name='newTargetHarian'),
    path('produksiHarian/newWaktuIstirahat/<str:produksiHarianInput>',viewsLiniProduksi_harian.newWaktuIstirahat, name='newWaktuIstirahat'),
    path('updateWaktuIstirahat/<str:update_id>', viewsLiniProduksi_harian.updateWaktuIstirahat, name='updateWaktuIstirahat'),
    path('deleteWaktuIstirahat/<str:delete_id>', viewsLiniProduksi_harian.deleteWaktuIstirahat, name='deleteWaktuIstirahat'),
    path('updateTargetTahunan/<str:update_id>', viewsLiniProduksi_harian.updateTargetTahunan, name='updateTargetTahunan'),
    path('deleteTargetTahunan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetTahunan, name='deleteTargetTahunan'),
    path('newTargetTahunan/',viewsLiniProduksi_harian.newTargetTahunan, name='newTargetTahunan'),
    path('updateTargetBulanan/<str:update_id>', viewsLiniProduksi_harian.updateTargetBulanan, name='updateTargetBulanan'),
    path('deleteTargetBulanan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetBulanan, name='deleteTargetBulanan'),
    path('newTargetBulanan/',viewsLiniProduksi_harian.newTargetBulanan, name='newTargetBulanan'),
    path('updateTargetMingguan/<str:update_id>', viewsLiniProduksi_harian.updateTargetMingguan, name='updateTargetMingguan'),
    path('deleteTargetMingguan/<str:delete_id>', viewsLiniProduksi_harian.deleteTargetMingguan, name='deleteTargetMingguan'),
    path('newTargetMingguan/',viewsLiniProduksi_harian.newTargetMingguan, name='newTargetMingguan'),
    path('newHariLibur/',viewsLiniProduksi_harian.hariLibur, name='newHariLibur'),
    path('newIstirahatNormal/',viewsLiniProduksi_harian.newWaktuIstirahatNormal, name='newIstirahatNormal'),
    path('newProduksiHarian/',viewsLiniProduksi_harian.newProduksiHarian, name='newProduksiHarian'),
    path('updateProduksiHarian/<str:update_id>', viewsLiniProduksi_harian.updateProduksiHarian, name='updateProduksiHarian'),
    path('deleteProduksiHarian/<str:delete_id>', viewsLiniProduksi_harian.deleteProduksiHarian, name='deleteProduksiHarian'),
    path('<str:idLiniProduksiInput>/<str:idStasiunKerjaInput>/', viewsStasiunKerjaDetail.stasiunKerjaDetail, name='stasiunKerjaDetail'),
    path('produksiTahunan/', viewsLiniProduksi_harian.tahunan, name='tahunan'),
    path('produksiBulanan/', viewsLiniProduksi_harian.bulanan, name='bulanan'),
    path('produksiMingguan/', viewsLiniProduksi_harian.mingguan, name='mingguan'),
    path('produksiHarian/', viewsLiniProduksi_harian.harian, name='harian'),
    path('produksi/', viewsLiniProduksi_harian.produksiHarian, name='produksiHarian'),
    path('tambahCapaianProduksi/<str:id>', viewsLiniProduksi_harian.tambahCapaian, name='tambahCapaian'),
    path('<str:idLiniProduksiInput>/', viewsStasiunKerja.stasiunKerja, name='stasiunKerja'),
    path('', views.index, name='index'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
