# Generated by Django 2.1.5 on 2021-08-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liniProduksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalLiniProduksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlahMaterialTersedia', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('jadwalKedatangan', models.TimeField()),
                ('jumlah_material', models.IntegerField()),
                ('is_konfirmasi', models.BooleanField(default=False)),
                ('jadwalKedatangan_aktual', models.TimeField(blank=True, null=True)),
                ('kebutuhanMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.KebutuhanMaterial')),
                ('liniProduksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.LiniProduksi', to_field='idLiniProduksi')),
                ('stasiunKerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liniProduksi.StasiunKerja', to_field='idStasiunKerja')),
            ],
        ),
    ]
