# Generated by Django 2.1.5 on 2021-08-11 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalliniproduksi',
            name='kebutuhanMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='liniProduksi.KebutuhanMaterial'),
        ),
    ]
